name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules # it is in github container not in ec2
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Deploy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./"
          target: "/home/ubuntu/workspace/procarma-info/_work/procarma-info/procarma-info"
          overwrite: true

      - name: SSH and restart app with PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/workspace/procarma-info/_work/procarma-info/procarma-info

            echo "🧹 Cleaning previous build..."
            rm -rf .next

            echo "🔨 Building app..."
            npm run build

            echo "🚀 Restarting app with PM2...."
            pm2 describe procarma-info > /dev/null 2>&1 && pm2 restart procarma-info || pm2 start ecosystem.config.js
